import type { IPermissionMatrix } from "../workspace/workspaceTypes";

export const DEFAULT_PERMISSION_MATRIX: IPermissionMatrix = {
  owner: {
    invite_member: true,
    remove_member: true,
    update_member: true,
    view_member: true,
    upload_video: true,
    edit_video: true,
    delete_video: true,
    view_video: true,
    view_workspace: true,
    update_workspace: true,
    delete_workspace: true,
    accept_video_upload_request: true,
    reject_video_upload_request: true,
    change_permission: true,
    transfer_ownership: true,
    authorize_channel: true,
  },
  admin: {
    invite_member: true,
    remove_member: true,
    update_member: true,
    view_member: false,
    upload_video: true,
    edit_video: true,
    delete_video: true,
    view_video: true,
    view_workspace: true,
    update_workspace: true,
    delete_workspace: false,
    accept_video_upload_request: true,
    reject_video_upload_request: true,
    change_permission: false,
    transfer_ownership: false,
    authorize_channel: false,
  },
  manager: {
    invite_member: true,
    remove_member: false,
    update_member: false,
    view_member: false,
    upload_video: true,
    edit_video: true,
    delete_video: true,
    view_video: true,
    view_workspace: true,
    update_workspace: false,
    delete_workspace: false,
    accept_video_upload_request: true,
    reject_video_upload_request: true,
    change_permission: false,
    transfer_ownership: false,
    authorize_channel: false,
  },
  editor: {
    invite_member: false,
    remove_member: false,
    update_member: false,
    view_member: false,
    upload_video: true,
    edit_video: true,
    delete_video: true,
    view_video: true,
    view_workspace: true,
    update_workspace: false,
    delete_workspace: false,
    accept_video_upload_request: false,
    reject_video_upload_request: false,
    change_permission: false,
    transfer_ownership: false,
    authorize_channel: false,
  },
  viewer: {
    invite_member: false,
    remove_member: false,
    update_member: false,
    view_member: false,
    upload_video: false,
    edit_video: false,
    delete_video: false,
    view_video: true,
    view_workspace: true,
    update_workspace: false,
    delete_workspace: false,
    accept_video_upload_request: false,
    reject_video_upload_request: false,
    change_permission: false,
    transfer_ownership: false,
    authorize_channel: false,
  },
};
